$:
  vscode:
    - docker:
        image: docker.cnb.cool/zhxycn/env:latest
      services:
        - vscode
        - docker
      env:
        CNB_WELCOME_EXECUTE_COMMAND: pnpm install && pnpm run dev